package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}
	repoRoot := filepath.Clean(filepath.Join(root, "..", ".."))
	pluginsDir := filepath.Join(repoRoot, "internal", "socialplugin")
	autoloadDir := filepath.Join(repoRoot, "internal", "socialpluginautoload")
	outPath := filepath.Join(autoloadDir, "imports_gen.go")

	entries, err := os.ReadDir(pluginsDir)
	if err != nil {
		fail(err)
	}

	var imports []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}
		pluginFile := filepath.Join(pluginsDir, name, "plugin.go")
		if _, err := os.Stat(pluginFile); err != nil {
			continue
		}
		imports = append(imports, fmt.Sprintf("_ %q", "qorvexus/internal/socialplugin/"+name))
	}
	sort.Strings(imports)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/generate_social_plugins. DO NOT EDIT.\n")
	buf.WriteString("package socialpluginautoload\n\n")
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, line := range imports {
			buf.WriteString("\t")
			buf.WriteString(line)
			buf.WriteString("\n")
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
