// Code generated by scripts/generate_social_plugins. DO NOT EDIT.
package socialpluginautoload

import (
	_ "qorvexus/internal/socialplugin/discord"
	_ "qorvexus/internal/socialplugin/qqbot"
	_ "qorvexus/internal/socialplugin/slack"
	_ "qorvexus/internal/socialplugin/telegram"
)
